environment:
  matrix:
    - RUST_VERSION: stable
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -Vv

build: off

test_script:
  - cargo test --all
